In [3]:
import numpy as np

a = np.array([[22, 5, 16, 9], 
              [13, 20, 19, 0],
              [5, 9, 1, 16],
              [27, 13, 15, 19]])
print('a\n', a)

b = np.array([[10, 5, 20, 20], 
              [5, 21, 22, 27],
              [26, 19, 22, 3],
              [27, 8, 18, 7]])

print('b\n', b)

c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

print('c\n', c)
print('d\n', d)


print('\nAddition\n', a + b)
print('\nSubtraction\n', a - b)
print('\nMultiplication\n', a * b)
print('\nMatrix Multiplication\n', np.dot(a, b))

print('\nAdd\n', c+d)
print('\nSubtract\n', c-d)
print('\nMultiplication\n', c*d)
print('\nMatrix Multiplication\n', np.dot(c, d))

print('\nA + 10 \n', a + 10)
print('\nB + 10 \n', b + 10)
print('\nc + 15 \n', c + 15)
print('\nd + 15 \n', d + 15)

print('\n(2 * A) + (2 * B)\n', np.multiply(2, a) + np.multiply(2, b))
print('\n(A + B) * 3\n', (a + b) * 3)
print('\n(A - B + A - B + B) * 4 \n', (a - b + a - b + b) * 4)

a
 [[22  5 16  9]
 [13 20 19  0]
 [ 5  9  1 16]
 [27 13 15 19]]
b
 [[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]
c
 [24  3 17  7 11  2 21  2 24 18  3 11 14 25  2 20]
d
 [ 3 15 24 22 19 24  4 29  6  3 20  1 11 25 26  6]

Addition
 [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]

Subtraction
 [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]

Multiplication
 [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]

Matrix Multiplication
 [[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]

Add
 [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]

Subtract
 [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]

Multiplication
 [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]

Matrix Multiplication
 2298

A + 10 
 [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]

B + 10 
 [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]

c + 